services:
  classifier-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "500:500"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./datasets:/datasets